<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <!-- Include PNG sprites and copy to output so Image Source can load them at runtime -->
    <Content Include="Assets\Sprites\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Background\bg.png" />
    <None Remove="Assets\Background\egg.png" />
    <None Remove="Assets\Background\logo.png" />
    <None Remove="Assets\Fonts\PixelifySans-Bold.ttf" />
    <None Remove="Assets\Fonts\PixelifySans-Medium.ttf" />
    <None Remove="Assets\Fonts\PixelifySans-Regular.ttf" />
    <None Remove="Assets\Fonts\PixelifySans-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Background\bg.png" />
    <Resource Include="Assets\Background\egg.png" />
    <Resource Include="Assets\Background\logo.png" />
    <Resource Include="Assets\Fonts\PixelifySans-Bold.ttf" />
    <Resource Include="Assets\Fonts\PixelifySans-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\PixelifySans-Regular.ttf" />
    <Resource Include="Assets\Fonts\PixelifySans-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Sprites\PetC\" />
    <Folder Include="Assets\Sprites\PetB\" />

  </ItemGroup>

</Project>
